package categories

const CREATE_CATEGORY_FAILED = "POST: CATEGORY CREATION FAILED"
const CREATE_CATEGORY_SUCCESS = "POST: CATEGORY CREATED"

const GET_CATEGORIES_FAILED = "GET: CATEGORIES FETCH FAILED"
