package comments

const CREATE_CATEGORY_SUCCESS = "POST: CATEGORY CREATED"
const CREATE_CATEGORY_FAILED = "POST: CATEGORY CREATION FAILED"

const NO_POSTID = "GET: NO REQUIRED POSTID FOUND IN URL"
const NO_PUBLICID = "GET: NO REQUIRED PUBLICID FOUND IN URL"

const GET_COMMENTS_FAILED = "GET: COMMENTS FETCH FAILED"
const GET_COMMENT_FAILED = "GET: COMMENT FETCH FAILED"

const COMMENT_MUTATION_FAILED = "POST: COMMENT MUTATION FAILED"
const COMMENT_MUTATION_SUCCESS = "POST: COMMENT MUTATION SUCCESSFUL"
