package users

const INVALID_USERNAME = "INVALID USERNAME"
const INVALID_PASSWORD = "INVALID PASSWORD"

const AUTH_USER_NOT_FOUND = "AUTH: USER NOT FOUND IN COOKIES"

const AUTH_FAILURE = "AUTH: AUTHENTICATION COOKIE NOT FOUND"
const AUTH_SUCCESS = "AUTH: AUTHENTICATION COOKIE FOUND"

const LOGOUT_SUCCESS = "AUTH: LOGOUT SUCCESSFUL; COOKIE DELETED"
const LOGOUT_FAILURE = "AUTH: LOGOUT FAILED; COOKIE NOT DELETED"

const NO_USER_PROFILE = "GET: NO USER FOUND IN PROFILE"

const REGISTRATION_FAILED = "AUTH: REGISTRATION FAILED"
const REGISTRATION_SUCCESS = "AUTH: REGISTRATION SUCCESSFUL"

const USERS_NOT_FOUND = "GET: NO USERS FOUND"
